name: Deploy to Amazon EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      # You may pin to the exact commit or the version.
      # uses: appleboy/ssh-action@bf84735fa9986d048980965656d55112e863f432
      uses: appleboy/ssh-action@v0.1.3
      with:
        # ssh host
        host: ${{ secrets.AWS_HOST }}
        # ssh username
        username: ${{ secrets.AWS_USER }}
        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        key: ${{ secrets.AWS_SUPER_KEY }}
        # execute commands (update, clean or migrate)
        script: /home/${{ secrets.AWS_PATH }} migrate
        # enable debug mode
        debug: true
