name: Coverage reporter

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Send coverage report to codeclimate
      uses: paambaati/codeclimate-action@v2.6.0
      with:
        coverageCommand: echo "Ignore rerun"
        coverageLocations: ${{github.workspace}}/coverage.xml:coverage.py
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
    - name: Send coverage report to codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
